export const EVENTS = {
  connection: 'connection',
  disconnect: 'disconnect',
  AUTHENTICATE_ME: 'AUTHENTICATE_ME',
  AUTHENTICATED:  'AUTHENTICATED',
  ROOM: 'ROOM',
  JOINED_ROOM: 'JOINED_ROOM',
  ROOM_MESSAGE: 'ROOM_MESSAGE',
  ADD_USER: 'ADD_USER',
  SEND_MESSAGE: 'SEND_MESSAGE',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  GET_PROFILE_DATA : "GET_PROFILE_DATA"
};
